name: Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: install dependencies
        run: |
          go get .
      - name: test with go cli
        run: go test -race ./...
